### ISSUE TITLE
Quit to menu option still carries over Despardo stacks

### ISSUE THREAD

**Issue by SheepishShepherd** [pi3n4t/KeepDesperadoTokens#4]
I noticed while tested out some mods, that when I die the stacks are properly removed. However, when I clicked on 'Quit to Menu' and did another run as Bandit with EITHER Desperado or Lights Out, I still had the Desperado stacks carrying over.

After gaining 10 stacks of Desperado, I quit to menu:
![Desparado_1](https://user-images.githubusercontent.com/36808587/152714092-94564ddf-e10d-44d9-9260-31442606fcb0.png)

Starting a new run (even with 'Lights Out') I start with 2 stacks:
![Desparado_2](https://user-images.githubusercontent.com/36808587/152714095-f1848b45-8cc1-4dac-ad8a-286d3b7968c7.png)

**Comment by pi3n4t** [comment]
Thank you for the report!

Once I get the build automation going I'll be fixing this.
